const APP_ANDROID_NAME = 'Marketing App';
const APP_APPLE_NAME = 'Marketing App';

const APP_ANDROID_VERSION = '1.0';
const APP_ANDROID_VERSION_CODE = 2;

const APP_APPLE_VERSION = '1.0';
const APP_APPLE_VERSION_CODE = 1;

export {
  APP_ANDROID_NAME,
  APP_APPLE_NAME,
  APP_ANDROID_VERSION,
  APP_ANDROID_VERSION_CODE,
  APP_APPLE_VERSION,
  APP_APPLE_VERSION_CODE,
};
